### PR TITLE
More modern report + filters

### PR DESCRIPTION
**Pull request by deneonet**
Made the report look a little bit more modern and added filters for unsafe string unmarshal and buffer reuse marshal, both are hidden on default.

### CODE REVIEW

**Comment by deneonet** [comment]
@matheusd approved?

**Review by alecthomas — APPROVED** [review]
Be nice to see a screenshot 🤔

**Comment by deneonet** [comment]
I'm on mobile, it looks bigger on desktop.

**Comment by matheusd** [comment]
Tbh, I prefer the older version. It was already filterable, had selectable columns (you could choose which metrics to include or not), had no unnecessary paging and included all assets (i.e. no dependency on third party code).

But at the end of the day, the decision on which one to use is up to the maintainers.

**Comment by deneonet** [comment]
Do you prefer the design of Windows XP or Windows 10? In the older version, you couldn't hide benchmarks with unsafe str marshal or buffer reuse marshal. And you can still decide which metrics to include and which not, all in the "Filter Benchmarks" button. What's the issue with paging? Users can decide how many entries to show and can search benchmarks. Lastly, it's way easier to just have a single .html file.

**Pull request merged**
