### PR TITLE
Removed buffer reusing from some serializers

### PR DESCRIPTION
**Pull request by deneonet**
Some serializer structs had buffer, which were reused, so I removed them + I updated benc to the latest version.

### CODE REVIEW

**Comment by alecthomas** [comment]
I think it's fine to remove reused buffers, but where applicable the serialisers should still be using preallocated buffers rather than letting the slices grow. The rationale is that if the encoder supports using pre-allocated buffers, the benchmarks should take advantage of them.

**Comment by deneonet** [comment]
I mean it's just easier to not allow buffer reusing, because writing multiple benchmarks just for buffer-reusing. There were also complains about it. But letting the slice grow on the baseline serializer, just kills the whole purpose of it, true. Let me fix it.

**Comment by deneonet** [comment]
Here a [https://github.com/alecthomas/go_serialization_benchmarks/pull/107](pull request), which changed, that all serializer allocate memory (so no buffer-reuse) and here an [https://github.com/alecthomas/go_serialization_benchmarks/issues/129](issue), that was opened to remove the buffer-reuse from my own serializer. It should be made clear, whether buffer reusing is allowed or not.

**Comment by deneonet** [comment]
Also, for example, bebop, doesn't support buffer reusing natively, it was added using a 'buf' field in the serializer struct. Now my question: Why didn't you add the buffer field on every serializer that supports it, like MUS or benc?

**Comment by 200sc** [comment]
Bebop does support buffer reuse natively, that's why it has a `MarshalBebopTo` method and it's docs suggest it's use in this way.

**Comment by deneonet** [comment]
Doesn't `MarshalBebopTo` require a buffer as argument?

**Comment by matheusd** [comment]
Quoting from the original issue:

> Basically, I don't have an issue with any particular optimisations as long as it's very clear what they are and what the tradeoffs are.

Measuring _with_ buffer reuse for the serializers that support is important to me, but I can see how that may different for users.

I see 2 possible solutions here:

- Add a `/bufferReuse` alternate benchmark for the serializers that do support it (same as the unsafe variants).
- Add a field in my [Dynamic Report PR](https://github.com/alecthomas/go_serialization_benchmarks/pull/147) which tags the serializers that support buffer reuse (same as the tagging done for unsafe string unmarshal).

**Comment by deneonet** [comment]
I would be for the first option, to also be able to compare benchmarks without buffer reuse.

**Comment by alecthomas** [comment]
> I would be for the first solution, to also be able to compare benchmarks without buffer reuse.

Agreed, and this echoes my original statement.  I do think that currently it is not obvious which serialisers are either using preallocated buffers, or reusing buffers. We should be consistent about that too.

**Comment by ymz-ncnk** [comment]
> I would be for the first solution, to also be able to compare benchmarks without buffer reuse.

I also think this is a best solution. But now, in the Totals table for each 
serializer, we have two records: marshal and unmarshal. Is this correct? If so, 
for a serializer that supports unsafe and reuse, we will have 8 records:
- marshal/serializer_name
- marshal/serializer_name/reuse
- marshal/serializer_name/unsafe
- marshal/serializer_name/unsafe_reuse
- unmarshal/serializer_name
- unmarshal/serializer_name/reuse
- unmarshal/serializer_name/unsafe
- unmarshal/serializer_name/unsafe_reuse

Isn't it too much? We could have only 4:
- serializer_name
- serializer_name/reuse
- serializer_name/unsafe
- serializer_name/unsafe_reuse

**Comment by matheusd** [comment]
> I also think this is a best solution. But now, in the Totals table for each serializer, we have two records: marshal and unmarshal. 

See the new HTML report card: https://htmlpreview.github.io/?https://github.com/alecthomas/go_serialization_benchmarks/blob/master/report/index.html

It aggregates marshal/unmarshal into a single line, so there is (e.g.) BENC and BENC/unsafe. With reuse, there would be either one or two additional lines (BENC, BENC/reuse, BENC/unsafe, BENC/unsafe/reuse).

**Comment by deneonet** [comment]
The table doesn't show up for me, just the metrics.

**Comment by matheusd** [comment]
Which browser are you using? Is JS enabled?

**Comment by deneonet** [comment]
Arc, I think that Js is enabled, otherwise any other site wouldn't work.

**Comment by deneonet** [comment]
On chrome is also doesn't work, on Floorp though.

**Comment by matheusd** [comment]
Some new form of blocking on chrome... :/

Will see if I can address it later.

**Pull request closed without merging**
