### PR TITLE
copi: a new modern high performance go serializer

### PR DESCRIPTION
**Pull request by nazarifard**
goserbench now supported copi.
please merge copi branch with master branch

### CODE REVIEW

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
Thanks!

**Comment by nazarifard** [comment]
> Thanks!

Thanks for your code review and approve.
Can I ask you to update to run stats.sh and update README.md tables that includes "Copi" result?

**Comment by alecthomas** [comment]
You can do this yourself by following the instructions and sending a PR.

**Comment by nazarifard** [comment]
> You can do this yourself by following the instructions and sending a PR.

No, I can't. firstly my laptop just has 4 core and I cant run benchmark with 8 cores, secondly I tried to run  ./stats.sh several times but it was failed all. Please If its possible run ./stats.sh to update and inclode "copi" serializer's results too.

**Comment by nazarifard** [comment]
> > You can do this yourself by following the instructions and sending a PR.
> 
> No, I can't. firstly my laptop just has 4 core and I cant run benchmark with 8 cores, secondly I tried to run ./stats.sh several times but it was failed all. Please If its possible run ./stats.sh to update and inclode "copi" serializer's results too.

any update?
@alecthomas

**Pull request merged**
