### PR TITLE
Make goavro v1 compatible and add goavro v2 benchmark tests

### LINKED ISSUE #64: Build broken: goavro v2 support
Currently unable to benchmark locally:

```
$ go get -u -t
# github.com/alecthomas/go_serialization_benchmarks
./structdef_avro.go:11:10: undefined: goavro.Record
```

Need to support v1 and v2 versions. Quick fix is changing current import from `"github.com/linkedin/goavro"` to `goavro "gopkg.in/linkedin/goavro.v1"`

### PR DESCRIPTION
**Pull request by taiyangc**
Fixes #64 

Should probably regenerate the report on golang 1.9 with the latest packages. I can do that as well if you feel comfortable or you can run it after merging @alecthomas

### CODE REVIEW

**Comment by alecthomas** [comment]
Brilliant, thanks!

I have no problem with you updating the benchmarks. As long as they're all done on the same machine, there's no issue. Thanks again!

**Comment by taiyangc** [comment]
OK, will update README shortly.

**Comment by taiyangc** [comment]
@alecthomas updated

**Comment by alecthomas** [comment]
Perfect, thank you!

**Pull request merged**
